version: '3.3'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php82
    depends_on:
      - db
    image: php:8.2-apache
    volumes:
      - ./php:/var/www/html
    ports:
      - 80:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - ./php/sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: 'db'
      PMA_USER: 'admin'
      PMA_PASSWORD: 'admin'
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80